### ISSUE TITLE
count(*) raises syntax error

### ISSUE THREAD

**Issue by Chocorean** [Mcdostone/sql-lint#1]
As of 02/23/22 10:10am, using https://laughing-euclid-cf6cad.netlify.app/ , sql-lint shows a ParsingError when it encounters the *.

Input    >> select count(\*) from employees
Output >> Unable to parse SQL: Parsing Error: Error { input: "(\*) from employees", code: Tag }

**Comment by Mcdostone** [comment]
it should work now!
