### ISSUE TITLE
Cannot create a table from another (using AS)

### ISSUE THREAD

**Issue by Chocorean** [Mcdostone/sql-lint#5]
```sql
create table zgeg as select * from queue where 1=2;
```
this raises parsing error: `Unable to parse SQL: Parsing Error: Error { input: "Create table Employee_1 as Select * from Employee where 1=2;", code: Tag }`

**Comment by Mcdostone** [comment]
According to [#table-definition](https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#table-definition) and [#subquery](https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#subquery), the correct syntax is:
```sql
create table pain_au_chocolat as (select * from chocolatine where 1=2);
```
